/*
Author: Sebastian G. Botasi <sgonzalez@bionimio.com.ar>
Date: 2012
Description: Program designed to receive TUIO protocol events and forward them to a Flash application through a local server. 
The idea of the program is to analyze and keep track of stains or not, 
and forward the application FLASH or spots between the scene captured by the webcam.
Turn has an FSM (finite state machine) who tested each one of more spots to substantiate its existence in time,
thus attempting to correct the care generated by the webcam.
 */

import TUIO.*;
import processing.net.*;

int port = 9001;
Server myServer;

TuioProcessing cliente;
NuevoMediador mediadorTUIO;

OpcionEditable lista;

PFont f;
String nameFont = "ArialMT-14.vlw";
int sizeFont = 14;

//variables for sending
byte zero = 0;
int hayGente = 1;
int noHayGente = 2;


int ancho = 400;
int alto = 400;

boolean activityExists = false;

void setup() {
  size( ancho, alto );
  background(0);
  f = loadFont(nameFont);
  textFont(f, sizeFont);
  lista = new OpcionEditable( "ACTIVAR ENVIO / DESACTIVAR ENVIO", 15, 110 );
  cliente  = new TuioProcessing( this );
  mediadorTUIO = new NuevoMediador( cliente );

  myServer = new Server(this, port);
}

void draw() {
  background(0);
  fill( 255 );
  textAlign(CENTER);
  text("*******************************************************************************", width/2, 20);
  text("SERVER_TUIO_FLASH", width/2, 35);
  text("IP: 127.0.0.1 || Puerto:"+str(port)+"", width/2, 60);
  text("*******************************************************************************", width/2, 80);


  text("Software by BIONIMIO <sgonzalez@bionimio.com.ar>", width/2, height-20);
  text("*******************************************************************************", width/2, 145);

  textAlign(CORNER);
  lista.draw();
  text("DATOS:", 10, 170);

//TUIO
  mediadorTUIO.actualizarPunteros();
  if (mediadorTUIO.cantPunteros > 0) {
    activityExists = true;
  }
  else {
    activityExists = false;
  }

//Servidor
  if ( lista.getEstado() ) {
    if (activityExists) {
      myServer.write(hayGente+",@");
    }
    else {
      myServer.write(noHayGente+",@");
    }
  }
    myServer.write(zero);

  text("Total Blobs...................................................................."+ str(mediadorTUIO.cantPunteros), 10, 190);
  text("Activity Exists................................................................"+ str(activityExists), 10, 210);
}

void mousePressed() {
  if ( lista.isColition( mouseX, mouseY ) ) {
    lista.setEstado();
  }
}



